### ISSUE TITLE
Keeps loading after selecting the address

### ISSUE THREAD

**Issue by filipehdbr** [tektite-software/omni-trezor#1]
When I select the address on the trezor connector it closes the window, comes back to https://www.omnitrezor.com/ but keeps loading forever. 

Ubuntu and Chrome latest

**Comment by filipehdbr** [comment]
@zeiv I "fixed" it by moving funds from the legacy account to the new account. My funds were on legacy and the issue no longer happens on the new wallet (not legacy)

**Comment by zeiv** [comment]
Ah yes, that would make sense.  I should probably include a note about that somewhere... this tool creates a P2SH bitcoin transaction to facilitate the OMNI transaction, which are only supported by the new segwit accounts in Trezor.  I'm going to go ahead and close this but feel free to reopen if you need!
