### ISSUE TITLE
Base issue on value to transfer 

### ISSUE THREAD

**Issue by rid-dim** [tektite-software/omni-trezor#2]
Heyhey,

I thought I'd mention that someone tried to send 1000 MAID through omnitrezor but the transaction ended up sending 4096 MAID.

[he posted about it in the safenetforum](https://safenetforum.org/t/trezor-support-for-omni-and-maid/26816/57) and it seems to be an error in base-auto-recognition at some point (while I guess we always want to be base10 and not base16 ; )

**Comment by zeiv** [comment]
Thanks @rid-dim, I'll see if I can take a look.  Appreciate the report -- I don't actively monitor safenetforum

**Comment by viacommits** [comment]
This should be fixed as of commit a72a18f
